In [327]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [328]:
# Load the dataset
df = pd.read_csv('D:\ML\ml-a3\Cars.csv')
# print out the dataset
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai i20 Magna,2013,320000,110000,Petrol,Individual,Manual,First Owner,18.5 kmpl,1197 CC,82.85 bhp,113.7Nm@ 4000rpm,5.0
8124,Hyundai Verna CRDi SX,2007,135000,119000,Diesel,Individual,Manual,Fourth & Above Owner,16.8 kmpl,1493 CC,110 bhp,"24@ 1,900-2,750(kgm@ rpm)",5.0
8125,Maruti Swift Dzire ZDi,2009,382000,120000,Diesel,Individual,Manual,First Owner,19.3 kmpl,1248 CC,73.9 bhp,190Nm@ 2000rpm,5.0
8126,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57 kmpl,1396 CC,70 bhp,140Nm@ 1800-3000rpm,5.0
8127,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57 kmpl,1396 CC,70 bhp,140Nm@ 1800-3000rpm,5.0

In [329]:
# Judging from the table and I want to keep it simple
# `Year` can be used for car age which should be correlated with `km_driven`
# -> I will convert a year to age of car
# `owner` and `seats` can be seen as a category or an incremental number.
# -> I will convert owner to an integer. Fourth & above will be just 4 and␣
#Test Drive as 5.
# -> In a second thought, I will only consider Is_FirstHand,␣
#Is_SecondHand, and Is_TestDrive.
# -> I will convert seats to be just an integer
# `fuel`, `seller_type`, `transmission` is category
# `mileage`, `engine`, `max_power`, `torque` is car specification. To me, I␣
#don't really that care.
# -> I will drop `torque` for sure.
# -> I am considering `engine` and `max_power`. It should be related.
# -> `mileage`? should this related to the other two above?
#Let's check the category
for col in ['fuel','seller_type','transmission', 'owner', 'seats']:
    series = df[col]
    print(f"Column {col} {len(series.unique())} unique value {series.unique()}")

Column fuel 4 unique value ['Diesel' 'Petrol' 'LPG' 'CNG']
Column seller_type 3 unique value ['Individual' 'Dealer' 'Trustmark Dealer']
Column transmission 2 unique value ['Manual' 'Automatic']
Column owner 5 unique value ['First Owner' 'Second Owner' 'Third Owner' 'Fourth & Above Owner'
 'Test Drive Car']
Column seats 10 unique value [ 5.  4. nan  7.  8.  6.  9. 10. 14.  2.]

In [330]:
# convert year to age
df['age'] = 2023 - df['year']
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats,age
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0,9
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0,9
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0,17
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0,13
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5.0,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai i20 Magna,2013,320000,110000,Petrol,Individual,Manual,First Owner,18.5 kmpl,1197 CC,82.85 bhp,113.7Nm@ 4000rpm,5.0,10
8124,Hyundai Verna CRDi SX,2007,135000,119000,Diesel,Individual,Manual,Fourth & Above Owner,16.8 kmpl,1493 CC,110 bhp,"24@ 1,900-2,750(kgm@ rpm)",5.0,16
8125,Maruti Swift Dzire ZDi,2009,382000,120000,Diesel,Individual,Manual,First Owner,19.3 kmpl,1248 CC,73.9 bhp,190Nm@ 2000rpm,5.0,14
8126,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57 kmpl,1396 CC,70 bhp,140Nm@ 1800-3000rpm,5.0,10
8127,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57 kmpl,1396 CC,70 bhp,140Nm@ 1800-3000rpm,5.0,10

In [331]:
order_map = {
'First':'FirstHand',
'Second':'SecondHand',
'Third':'SecondHand',
'Fourth':'SecondHand',
'Test':'TestDrive'
}
df['is'] = df['owner'].apply(lambda x: order_map[x.split()[0]])
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats,age,is
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0,9,FirstHand
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0,9,SecondHand
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0,17,SecondHand
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0,13,FirstHand
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5.0,16,FirstHand
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai i20 Magna,2013,320000,110000,Petrol,Individual,Manual,First Owner,18.5 kmpl,1197 CC,82.85 bhp,113.7Nm@ 4000rpm,5.0,10,FirstHand
8124,Hyundai Verna CRDi SX,2007,135000,119000,Diesel,Individual,Manual,Fourth & Above Owner,16.8 kmpl,1493 CC,110 bhp,"24@ 1,900-2,750(kgm@ rpm)",5.0,16,SecondHand
8125,Maruti Swift Dzire ZDi,2009,382000,120000,Diesel,Individual,Manual,First Owner,19.3 kmpl,1248 CC,73.9 bhp,190Nm@ 2000rpm,5.0,14,FirstHand
8126,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57 kmpl,1396 CC,70 bhp,140Nm@ 1800-3000rpm,5.0,10,FirstHand
8127,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57 kmpl,1396 CC,70 bhp,140Nm@ 1800-3000rpm,5.0,10,FirstHand

In [332]:
# I notice some nan in the dataset.
print(f"Number of nan in 'seats: ",len(df['seats'].loc[df['seats'].isna()]))
# OMG 221 of the data is nan.
# At this point, I would drop them, but I want to take a look at the car name␣
#first
print(df['name'].loc[df['seats'].isna()].unique())
# It possible to fill in the seat number.
# I the real work, I would spend time fill in the nan
# But this is not real, I will drop the nan.
df.dropna(inplace=True)
df

Number of nan in 'seats:  221
['Maruti Swift 1.3 VXi' 'Fiat Palio 1.2 ELX' 'Tata Indica DLS'
 'Maruti Swift VDI BSIV W ABS' 'Maruti Swift VDI BSIV'
 'BMW X1 sDrive 20D xLine' 'Toyota Etios GD' 'Maruti Omni E 8 Str STD'
 'Mahindra Willys CJ 3B 4X4' 'Hyundai Santro Xing XL'
 'Toyota Etios Liva Diesel TRD Sportivo' 'Maruti Estilo LXI'
 'Maruti Alto K10 LXI' 'Hyundai Santro Xing XG' 'Mahindra Bolero GLX'
 'Maruti Zen Estilo VXI BSIV W ABS' 'Hyundai Santro Xing XP'
 'Hyundai Santro GLS I - Euro I' 'Skoda Superb 1.8 TSI'
 'Maruti Esteem Vxi - BSII' 'Mahindra Xylo E8 BS4'
 'Fiat Punto 1.3 Emotion' 'Toyota Qualis Fleet A3'
 'Hyundai Santro GLS I - Euro II'
 'Hyundai Santro Xing XG AT eRLX Euro III' 'Toyota Etios Liva GD'
 'Maruti Omni BSIII 8-STR W/ IMMOBILISER' 'Mahindra Jeep Classic'
 'Hyundai Santro GS zipDrive - Euro II' 'Mahindra Ingenio CRDe'
 'Mahindra Jeep CL 500 MDI' 'Maruti Swift Dzire VDI Optional'
 'Hyundai Santro Xing XS eRLX Euro III'
 'Tata Indica Vista Aqua 1.3 Quadrajet (ABS)' 'Mahindra Jeep MM 540'
 'Hyundai Santro GS zipPlus' 'Hyundai Santro LP zipPlus'
 'Hyundai Santro Xing GL CNG' 'Tata Sumo EX BS IV'
 'Hyundai Santro GS zipDrive - Euro I' 'Hyundai Santro Xing GL PLUS CNG'
 'Toyota Qualis GS G1' 'Toyota Etios Liva G' 'Toyota Etios V'
 'Maruti Omni LPG STD BSIV' 'Hyundai Santro Xing Base'
 'Honda City 1.5 GXI CVT' 'Tata Indica Vista Quadrajet LS'
 'Ford Fiesta 1.6 SXI ABS Duratec' 'Hyundai Santro Xing XG AT'
 'Mahindra Jeep MM 550 XDB' 'Ford Fiesta 1.4 SXi TDCi'
 'Toyota Premio Base' 'Mahindra Bolero LX' 'Tata Estate Std'
 'Hyundai Santro Xing XO eRLX Euro II' 'Volkswagen Multivan TDI'
 'Hyundai Santro Xing XS eRLX Euro II' 'Toyota Etios Liva GD SP'
 'Maruti Esteem LX' 'Hyundai Santro LE'
 'Hyundai Santro Xing XL eRLX Euro II' 'Maruti Swift 1.3 LXI'
 'Toyota Qualis GS C1' 'Fiat Palio 1.2' 'Toyota Qualis FS F7'
 'Hyundai Santro Xing XG AT eRLX Euro II' 'Maruti Esteem Lxi'
 'Ford Figo Aspire Facelift' 'Maruti Swift 1.3 ZXI' 'Mahindra Marshal DI'
 'Hyundai Santro AT' 'Tata Indica DLX' 'Hyundai Santro DX'
 'Hyundai Santro LP - Euro II' 'Toyota Etios GD SP'
 'Hyundai Santro LS zipPlus' 'Hyundai Santro AT CNG'
 'BMW 5 Series 520d Sedan' 'Ford Ikon 1.8 D' 'Peugeot 309 GLD'
 'Hyundai Santro Xing ABS' 'Hyundai Santro Xing XO' 'Toyota Etios VD'
 'Hyundai Accent Gvs']

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats,age,is
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0,9,FirstHand
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0,9,SecondHand
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0,17,SecondHand
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0,13,FirstHand
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5.0,16,FirstHand
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai i20 Magna,2013,320000,110000,Petrol,Individual,Manual,First Owner,18.5 kmpl,1197 CC,82.85 bhp,113.7Nm@ 4000rpm,5.0,10,FirstHand
8124,Hyundai Verna CRDi SX,2007,135000,119000,Diesel,Individual,Manual,Fourth & Above Owner,16.8 kmpl,1493 CC,110 bhp,"24@ 1,900-2,750(kgm@ rpm)",5.0,16,SecondHand
8125,Maruti Swift Dzire ZDi,2009,382000,120000,Diesel,Individual,Manual,First Owner,19.3 kmpl,1248 CC,73.9 bhp,190Nm@ 2000rpm,5.0,14,FirstHand
8126,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57 kmpl,1396 CC,70 bhp,140Nm@ 1800-3000rpm,5.0,10,FirstHand
8127,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57 kmpl,1396 CC,70 bhp,140Nm@ 1800-3000rpm,5.0,10,FirstHand

In [333]:
# Now, I convertthe `seats`
df['seats'] = df['seats'].astype(int)
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats,age,is
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5,9,FirstHand
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5,9,SecondHand
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5,17,SecondHand
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5,13,FirstHand
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5,16,FirstHand
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai i20 Magna,2013,320000,110000,Petrol,Individual,Manual,First Owner,18.5 kmpl,1197 CC,82.85 bhp,113.7Nm@ 4000rpm,5,10,FirstHand
8124,Hyundai Verna CRDi SX,2007,135000,119000,Diesel,Individual,Manual,Fourth & Above Owner,16.8 kmpl,1493 CC,110 bhp,"24@ 1,900-2,750(kgm@ rpm)",5,16,SecondHand
8125,Maruti Swift Dzire ZDi,2009,382000,120000,Diesel,Individual,Manual,First Owner,19.3 kmpl,1248 CC,73.9 bhp,190Nm@ 2000rpm,5,14,FirstHand
8126,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57 kmpl,1396 CC,70 bhp,140Nm@ 1800-3000rpm,5,10,FirstHand
8127,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57 kmpl,1396 CC,70 bhp,140Nm@ 1800-3000rpm,5,10,FirstHand

In [334]:
# I will conert mileage, engine, power to something we can process
df['mileage'] = df['mileage'].apply(lambda x: x.split()[0]).astype(float)
df['engine'] = df['engine'].apply(lambda x: x.split()[0]).astype(int)
df['max_power'] = df['max_power'].apply(lambda x: x.split()[0]).astype(float)
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats,age,is
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.40,1248,74.00,190Nm@ 2000rpm,5,9,FirstHand
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14,1498,103.52,250Nm@ 1500-2500rpm,5,9,SecondHand
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.70,1497,78.00,"12.7@ 2,700(kgm@ rpm)",5,17,SecondHand
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.00,1396,90.00,22.4 kgm at 1750-2750rpm,5,13,FirstHand
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.10,1298,88.20,"11.5@ 4,500(kgm@ rpm)",5,16,FirstHand
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai i20 Magna,2013,320000,110000,Petrol,Individual,Manual,First Owner,18.50,1197,82.85,113.7Nm@ 4000rpm,5,10,FirstHand
8124,Hyundai Verna CRDi SX,2007,135000,119000,Diesel,Individual,Manual,Fourth & Above Owner,16.80,1493,110.00,"24@ 1,900-2,750(kgm@ rpm)",5,16,SecondHand
8125,Maruti Swift Dzire ZDi,2009,382000,120000,Diesel,Individual,Manual,First Owner,19.30,1248,73.90,190Nm@ 2000rpm,5,14,FirstHand
8126,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57,1396,70.00,140Nm@ 1800-3000rpm,5,10,FirstHand
8127,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57,1396,70.00,140Nm@ 1800-3000rpm,5,10,FirstHand

In [335]:
# Now I drop the feature I dont want.
df = df.drop(columns=['name','year','owner','torque'])
df

,selling_price,km_driven,fuel,seller_type,transmission,mileage,engine,max_power,seats,age,is
0,450000,145500,Diesel,Individual,Manual,23.40,1248,74.00,5,9,FirstHand
1,370000,120000,Diesel,Individual,Manual,21.14,1498,103.52,5,9,SecondHand
2,158000,140000,Petrol,Individual,Manual,17.70,1497,78.00,5,17,SecondHand
3,225000,127000,Diesel,Individual,Manual,23.00,1396,90.00,5,13,FirstHand
4,130000,120000,Petrol,Individual,Manual,16.10,1298,88.20,5,16,FirstHand
...,...,...,...,...,...,...,...,...,...,...,...
8123,320000,110000,Petrol,Individual,Manual,18.50,1197,82.85,5,10,FirstHand
8124,135000,119000,Diesel,Individual,Manual,16.80,1493,110.00,5,16,SecondHand
8125,382000,120000,Diesel,Individual,Manual,19.30,1248,73.90,5,14,FirstHand
8126,290000,25000,Diesel,Individual,Manual,23.57,1396,70.00,5,10,FirstHand
8127,290000,25000,Diesel,Individual,Manual,23.57,1396,70.00,5,10,FirstHand

In [336]:
df = pd.concat([df, pd.get_dummies(df['fuel'], prefix='fuel', dtype=int)],axis=1)
df = pd.concat([df, pd.get_dummies(df['transmission'], prefix='transmission',dtype=int)], axis=1)
df = pd.concat([df, pd.get_dummies(df['seller_type'], prefix='seller',dtype=int)], axis=1)
df = pd.concat([df, pd.get_dummies(df['is'], prefix='is', dtype=int)], axis=1)
df = df.drop(columns=['fuel','seller_type','transmission', 'is'])
df

,selling_price,km_driven,mileage,engine,max_power,seats,age,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,transmission_Automatic,transmission_Manual,seller_Dealer,seller_Individual,seller_Trustmark Dealer,is_FirstHand,is_SecondHand,is_TestDrive
0,450000,145500,23.40,1248,74.00,5,9,0,1,0,0,0,1,0,1,0,1,0,0
1,370000,120000,21.14,1498,103.52,5,9,0,1,0,0,0,1,0,1,0,0,1,0
2,158000,140000,17.70,1497,78.00,5,17,0,0,0,1,0,1,0,1,0,0,1,0
3,225000,127000,23.00,1396,90.00,5,13,0,1,0,0,0,1,0,1,0,1,0,0
4,130000,120000,16.10,1298,88.20,5,16,0,0,0,1,0,1,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,320000,110000,18.50,1197,82.85,5,10,0,0,0,1,0,1,0,1,0,1,0,0
8124,135000,119000,16.80,1493,110.00,5,16,0,1,0,0,0,1,0,1,0,0,1,0
8125,382000,120000,19.30,1248,73.90,5,14,0,1,0,0,0,1,0,1,0,1,0,0
8126,290000,25000,23.57,1396,70.00,5,10,0,1,0,0,0,1,0,1,0,1,0,0
8127,290000,25000,23.57,1396,70.00,5,10,0,1,0,0,0,1,0,1,0,1,0,0

In [337]:
# Let's check a quick correlation
abs(df.corr()).style.background_gradient(cmap='coolwarm').format(precision=2)

In [338]:
# As expected, mileage engine max_power are quite related.
# Before I make a decision, let's check the engine.
df['engine'].unique()
# I now think this does not make sense. I normally see an engine with 1200cc,1300cc, 1400cc, 1500cc 1600cc, 1800cc, 2000cc.
# So I will futhur preprocessing them by devided by 100 and keep the integer part

array([1248, 1498, 1497, 1396, 1298, 1197, 1061,  796, 1364, 1399, 1461,
        993, 1198, 1199,  998, 1591, 2179, 1368, 2982, 2494, 2143, 2477,
       1462, 2755, 1968, 1798, 1196, 1373, 1598, 1998, 1086, 1194, 1172,
       1405, 1582,  999, 2487, 1999, 3604, 2987, 1995, 1451, 1969, 2967,
       2497, 1797, 1991, 2362, 1493, 1599, 1341, 1794,  799, 1193, 2696,
       1495, 1186, 1047, 2498, 2956, 2523, 1120,  624, 1496, 1984, 2354,
        814,  793, 1799,  936, 1956, 1997, 1499, 1948, 2997, 2489, 2499,
       2609, 2953, 1150, 1994, 1388, 1527, 2199,  995, 2993, 1586, 1390,
        909, 2393, 3198, 1339, 2835, 2092, 1595, 2496, 1596, 1597, 2596,
       2148, 1299, 1590, 2231, 2694, 2200, 1795, 1896, 1796, 1422, 1489,
       2359, 2197, 2999, 1781, 2650, 1343, 2446, 3498, 2198, 2776, 1950])

In [339]:
df['engine'] = (df['engine'] / 100).astype(int)
df

,selling_price,km_driven,mileage,engine,max_power,seats,age,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,transmission_Automatic,transmission_Manual,seller_Dealer,seller_Individual,seller_Trustmark Dealer,is_FirstHand,is_SecondHand,is_TestDrive
0,450000,145500,23.40,12,74.00,5,9,0,1,0,0,0,1,0,1,0,1,0,0
1,370000,120000,21.14,14,103.52,5,9,0,1,0,0,0,1,0,1,0,0,1,0
2,158000,140000,17.70,14,78.00,5,17,0,0,0,1,0,1,0,1,0,0,1,0
3,225000,127000,23.00,13,90.00,5,13,0,1,0,0,0,1,0,1,0,1,0,0
4,130000,120000,16.10,12,88.20,5,16,0,0,0,1,0,1,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,320000,110000,18.50,11,82.85,5,10,0,0,0,1,0,1,0,1,0,1,0,0
8124,135000,119000,16.80,14,110.00,5,16,0,1,0,0,0,1,0,1,0,0,1,0
8125,382000,120000,19.30,12,73.90,5,14,0,1,0,0,0,1,0,1,0,1,0,0
8126,290000,25000,23.57,13,70.00,5,10,0,1,0,0,0,1,0,1,0,1,0,0
8127,290000,25000,23.57,13,70.00,5,10,0,1,0,0,0,1,0,1,0,1,0,0

In [340]:
# Final recheck the corr
abs(df.corr()).style.background_gradient(cmap='coolwarm').format(precision=2)

In [341]:
# I will drop `mileage` and `max_power` since engine alone is related to both of them.
df = df.drop(columns=['mileage','max_power'])

In [342]:
df.to_csv('D:\ML\ml-a3\dataset\preprocess_cars.csv')

In [343]:
#loading the preprocessed data file
df=pd.read_csv('D:\ML\ml-a3\dataset\preprocess_cars.csv')
df.head()

,Unnamed: 0,selling_price,km_driven,engine,seats,age,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,transmission_Automatic,transmission_Manual,seller_Dealer,seller_Individual,seller_Trustmark Dealer,is_FirstHand,is_SecondHand,is_TestDrive
0,0,450000,145500,12,5,9,0,1,0,0,0,1,0,1,0,1,0,0
1,1,370000,120000,14,5,9,0,1,0,0,0,1,0,1,0,0,1,0
2,2,158000,140000,14,5,17,0,0,0,1,0,1,0,1,0,0,1,0
3,3,225000,127000,13,5,13,0,1,0,0,0,1,0,1,0,1,0,0
4,4,130000,120000,12,5,16,0,0,0,1,0,1,0,1,0,1,0,0

In [344]:
df = df.drop(columns=['Unnamed: 0'])

In [345]:
df['selling_price'].max() #29999 to 10000000

10000000

In [346]:
import pandas as pd

# Assuming you have a DataFrame named 'df' with your data
# Define the bins for discretization
bins = [20000, 100000, 500000, 1000000, 10000000]

# Define labels for the bins
labels = [0, 1, 2, 3]

# Create a new column 'price_category' with the discretized values
df['price_category'] = pd.cut(df['selling_price'], bins=bins, labels=labels, include_lowest=True)

# Display the resulting DataFrame
print(df[['selling_price', 'price_category']])

      selling_price price_category
0            450000              1
1            370000              1
2            158000              1
3            225000              1
4            130000              1
...             ...            ...
7901         320000              1
7902         135000              1
7903         382000              1
7904         290000              1
7905         290000              1

[7906 rows x 2 columns]

In [347]:
df['price_category'].unique()

[1, 0, 2, 3]
Categories (4, int64): [0 < 1 < 2 < 3]

In [348]:
#x is our strong features based on the heatmap
X = df[['engine','age']]

#y is simply the target we want to estimate
y = df["price_category"]

In [349]:
#splitting the dataset into train and test datasets
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3, random_state = 42)

In [350]:
engine = X_train['engine'].median()

In [351]:
# Let's check shapes of all X_train, X_test, y_train, y_test
print("Shape of X_train: ", X_train.shape)
print("Shape of X_test: ", X_test.shape)
print("Shape of y_train: ", y_train.shape)
print("Shape of y_test: ", y_test.shape)

Shape of X_train:  (5534, 2)
Shape of X_test:  (2372, 2)
Shape of y_train:  (5534,)
Shape of y_test:  (2372,)

In [353]:
from sklearn.preprocessing import StandardScaler
# feature scaling helps improve reach convergence faster
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)

In [354]:
# add intercept to our X
intercept = np.ones((X_train.shape[0], 1))
X_train   = np.concatenate((intercept, X_train), axis=1)  #add intercept
intercept = np.ones((X_test.shape[0], 1))
X_test    = np.concatenate((intercept, X_test), axis=1)  #add intercept

In [355]:
# make sure our y is in the shape of (m, k)
# we will convert our output vector in 
# matrix where no. of columns is equal to the no. of classes. 
# The values in the matrix will be 0 or 1. For instance the rows 
# where we have output 2 the column 2 will contain 1 and the rest are all 0.
# in simple words, y will be of shape (m, k)
k = len(set(y))  # no. of class  (can also use np.unique)
m = X_train.shape[0]  # no.of samples
n = X_train.shape[1]  # no. of features
Y_train_encoded = np.zeros((m, k))
for each_class in range(k):
    cond = y_train==each_class
    Y_train_encoded[np.where(cond), each_class] = 1

In [356]:
# Import necessary libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Load your dataset (assuming you have it in a DataFrame)
# Replace 'your_data.csv' with the actual path to your dataset file
#data = pd.read_csv('D:\ML\ml-a3\dataset\preprocess_cars.csv')

# Define the features (X) and the target variable (y)
#X = df['engine','age']  # Features
#y = df['price_category']  # Target variable

# Split the data into training and testing sets (e.g., 80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a logistic regression model
model = LogisticRegression()

# Train the model on the training data
model.fit(X_train, y_train)

# Make predictions on the test data
y_pred = model.predict(X_test)

# Evaluate the model's performance
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

# Print the results
print("Accuracy:", accuracy)
print("Confusion Matrix:")
print(confusion)
print("Classification Report:")
print(classification_rep)

Accuracy: 0.7452591656131479
Confusion Matrix:
[[ 22  35   0   0]
 [  9 719 127   2]
 [  0 140 343  22]
 [  0   3  65  95]]
Classification Report:
              precision    recall  f1-score   support

           0       0.71      0.39      0.50        57
           1       0.80      0.84      0.82       857
           2       0.64      0.68      0.66       505
           3       0.80      0.58      0.67       163

    accuracy                           0.75      1582
   macro avg       0.74      0.62      0.66      1582
weighted avg       0.75      0.75      0.74      1582

C:\Users\Dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [362]:
# Assuming you have trained your logistic regression model and made predictions as 'y_pred'

# Count the number of correct predictions
correct_predictions = 0

# Iterate through each prediction and true label
for pred, true_label in zip(y_pred, y_test):
    if pred == true_label:
        correct_predictions += 1

# Calculate accuracy
accuracy = correct_predictions / len(y_test)

# Print the accuracy
print(f'Accuracy: {accuracy:.2f}')


def precision(self, true_labels, predicted_labels, class_label):
        true_positive = np.sum((true_labels == class_label) & (predicted_labels == class_label))
        false_positive = np.sum((true_labels != class_label) & (predicted_labels == class_label))
        precision = true_positive / (true_positive + false_positive)
        return precision

Accuracy: 0.75

TypeError: unsupported format string passed to function.__format__

In [ ]:
import numpy as np

class LogisticRegression:
    def __init__(self, model):
        self.model = model

    def calculate_accuracy():
        # Assuming you have a model named 'model' and you're making predictions on a dataset 'X_test'
        #predicted_labels = self.model.predict(X_test)
        
        # Calculate the number of correct predictions
        correct_predictions = np.sum(y == predicted_labels)
        total_predictions = len(true_labels)
        
        # Calculate accuracy
        accuracy = correct_predictions / total_predictions
        
        return accuracy

In [357]:
import numpy as np

class LogisticRegression:
    def __init__(self, model):
        self.model = model

    def calculate_accuracy(self, true_labels, X_test):
        # Assuming you have a model named 'model' and you're making predictions on a dataset 'X_test'
        predicted_labels = self.model.predict(X_test)
        
        # Calculate the number of correct predictions
        correct_predictions = np.sum(true_labels == predicted_labels)
        total_predictions = len(true_labels)
        
        # Calculate accuracy
        accuracy = correct_predictions / total_predictions
        
        return accuracy

    def precision(self, true_labels, predicted_labels, class_label):
        true_positive = np.sum((true_labels == class_label) & (predicted_labels == class_label))
        false_positive = np.sum((true_labels != class_label) & (predicted_labels == class_label))
        precision = true_positive / (true_positive + false_positive)
        return precision

    def recall(self, true_labels, predicted_labels, class_label):
        true_positive = np.sum((true_labels == class_label) & (predicted_labels == class_label))
        false_negative = np.sum((true_labels == class_label) & (predicted_labels != class_label))
        recall = true_positive / (true_positive + false_negative)
        return recall

    def f1_score(self, true_labels, predicted_labels, class_label):
        prec = self.precision(true_labels, predicted_labels, class_label)
        rec = self.recall(true_labels, predicted_labels, class_label)
        return 2 * (prec * rec) / (prec + rec)

    def macro_precision(self, true_labels, predicted_labels, num_classes):
        precisions = [self.precision(true_labels, predicted_labels, class_label) for class_label in range(num_classes)]
        return np.mean(precisions)

    def macro_recall(self, true_labels, predicted_labels, num_classes):
        recalls = [self.recall(true_labels, predicted_labels, class_label) for class_label in range(num_classes)]
        return np.mean(recalls)

    def macro_f1_score(self, true_labels, predicted_labels, num_classes):
        f1_scores = [self.f1_score(true_labels, predicted_labels, class_label) for class_label in range(num_classes)]
        return np.mean(f1_scores)

    def weighted_precision(self, true_labels, predicted_labels, num_classes, class_weights):
        precisions = [self.precision(true_labels, predicted_labels, class_label) for class_label in range(num_classes)]
        weighted_precisions = [class_weights[class_label] * precisions[class_label] for class_label in range(num_classes)]
        return np.sum(weighted_precisions) / np.sum(class_weights)

    def weighted_recall(self, true_labels, predicted_labels, num_classes, class_weights):
        recalls = [self.recall(true_labels, predicted_labels, class_label) for class_label in range(num_classes)]
        weighted_recalls = [class_weights[class_label] * recalls[class_label] for class_label in range(num_classes)]
        return np.sum(weighted_recalls) / np.sum(class_weights)

    def weighted_f1_score(self, true_labels, predicted_labels, num_classes, class_weights):
        f1_scores = [self.f1_score(true_labels, predicted_labels, class_label) for class_label in range(num_classes)]
        weighted_f1_scores = [class_weights[class_label] * f1_scores[class_label] for class_label in range(num_classes)]
        return np.sum(weighted_f1_scores) / np.sum(class_weights)

# Example usage:
# Instantiate the LogisticRegression class with your model
# Replace 'your_model' with the actual model you have
logistic_regression = LogisticRegression(model)

# Replace 'true_labels' and 'predicted_labels' with your actual data
#true_labels = np.array([0, 1, 1, 0, 1, 0])
#predicted_labels = np.array([0, 1, 0, 1, 0, 1])


# Calculate class weights (replace with your own class distribution)
class_weights = [0.2, 0.3, 0.2, 0.3]

# Calculate and print the metrics
accuracy = logistic_regression.calculate_accuracy(true_labels, X_test)
print("Accuracy:", accuracy)

macro_precision = logistic_regression.macro_precision(true_labels, predicted_labels, num_classes=4)
print("Macro Precision:", macro_precision)

macro_recall = logistic_regression.macro_recall(true_labels, predicted_labels, num_classes=4)
print("Macro Recall:", macro_recall)

macro_f1_score = logistic_regression.macro_f1_score(true_labels, predicted_labels, num_classes=4)
print("Macro F1 Score:", macro_f1_score)

weighted_precision = logistic_regression.weighted_precision(true_labels, predicted_labels, num_classes=4, class_weights=class_weights)
print("Weighted Precision:", weighted_precision)

weighted_recall = logistic_regression.weighted_recall(true_labels, predicted_labels, num_classes=4, class_weights=class_weights)
print("Weighted Recall:", weighted_recall)

weighted_f1_score = logistic_regression.weighted_f1_score(true_labels, predicted_labels, num_classes=4, class_weights=class_weights)
print("Weighted F1 Score:", weighted_f1_score)

ValueError: ('Lengths must match to compare', (7906,), (1582,))

In [ ]:
import numpy as np

class LogisticRegression:
    predicted_labels = model.predict(X_test)
    true_labels = df['price_category']
    def __init__(self, model):
        self.model = model
    def calculate_accuracy(self, y_test, y_pred):
        # Assuming you have a model named 'model' and you're making predictions on a dataset 'X_test'
        predicted_labels = model.predict(X_test)
        true_labels = df['price_category']
        predicted_labels = self.model.predict(X_test)
        
        # Calculate the number of correct predictions
        correct_predictions = np.sum(true_labels == predicted_labels)
        total_predictions = len(true_labels)
        
        # Calculate accuracy
        accuracy = correct_predictions / total_predictions
        
        return accuracy

# Example usage:
# Instantiate the LogisticRegression class with your model
# Replace 'your_model' with the actual model you have
# Replace 'X_test' with your test data
#logistic_regression = LogisticRegression(your_model)

# Replace 'true_labels' with your true labels
#accuracy = logistic_regression.calculate_accuracy(true_labels, X_test)

#print("Accuracy:", accuracy)

    
# Function to calculate precision for a specific class
    def precision(self,true_labels, predicted_labels, class_label):
        true_positive = np.sum((true_labels == class_label) & (predicted_labels == class_label))
        false_positive = np.sum((true_labels != class_label) & (predicted_labels == class_label))
        precision = true_positive / (true_positive + false_positive)
        return precision

# Function to calculate recall for a specific class
    def recall(self,true_labels, predicted_labels, class_label):
        true_positive = np.sum((true_labels == class_label) & (predicted_labels == class_label))
        false_negative = np.sum((true_labels == class_label) & (predicted_labels != class_label))
        return true_positive / (true_positive + false_negative)
    

    # Function to calculate F1-score for a specific class
    def f1_score(true_labels, predicted_labels, class_label):
        prec = precision(true_labels, predicted_labels, class_label)
        rec = recall(true_labels, predicted_labels, class_label)
        return 2 * (prec * rec) / (prec + rec)

# Function to calculate macro-precision
    def macro_precision(true_labels, predicted_labels, num_classes):
        precisions = [precision(true_labels, predicted_labels, class_label) for class_label in range(num_classes)]
        return np.mean(precisions)

# Function to calculate macro-recall
    def macro_recall(true_labels, predicted_labels, num_classes):
        recalls = [recall(true_labels, predicted_labels, class_label) for class_label in range(num_classes)]
        return np.mean(recalls)

# Function to calculate macro-F1
    def macro_f1_score(true_labels, predicted_labels, num_classes):
        f1_scores = [f1_score(true_labels, predicted_labels, class_label) for class_label in range(num_classes)]
        return np.mean(f1_scores)

# Function to calculate weighted precision
    def weighted_precision(true_labels, predicted_labels, num_classes, class_weights):
        precisions = [precision(true_labels, predicted_labels, class_label) for class_label in range(num_classes)]
        weighted_precisions = [class_weights[class_label] * precisions[class_label] for class_label in range(num_classes)]
        return np.sum(weighted_precisions) / np.sum(class_weights)

# Function to calculate weighted recall
    def weighted_recall(true_labels, predicted_labels, num_classes, class_weights):
        recalls = [recall(true_labels, predicted_labels, class_label) for class_label in range(num_classes)]
        weighted_recalls = [class_weights[class_label] * recalls[class_label] for class_label in range(num_classes)]
        return np.sum(weighted_recalls) / np.sum(class_weights)

# Function to calculate weighted F1-score
    def weighted_f1_score(true_labels, predicted_labels, num_classes, class_weights):
        f1_scores = [f1_score(true_labels, predicted_labels, class_label) for class_label in range(num_classes)]
        weighted_f1_scores = [class_weights[class_label] * f1_scores[class_label] for class_label in range(num_classes)]
        return np.sum(weighted_f1_scores) / np.sum(class_weights)
# Calculate class weights (replace with your own class distribution)
class_weights = [0.2, 0.3, 0.2, 0.3]

# Calculate and print the metrics
print("Accuracy:", accuracy(true_labels, predicted_labels))
print("Macro Precision:", macro_precision(true_labels, predicted_labels, num_classes=4))
print("Macro Recall:", macro_recall(true_labels, predicted_labels, num_classes=4))
print("Macro F1 Score:", macro_f1_score(true_labels, predicted_labels, num_classes=4))
print("Weighted Precision:", weighted_precision(true_labels, predicted_labels, num_classes=4, class_weights=class_weights))
print("Weighted Recall:", weighted_recall(true_labels, predicted_labels, num_classes=4, class_weights=class_weights))
print("Weighted F1 Score:", weighted_f1_score(true_labels, predicted_labels, num_classes=4, class_weights=class_weights))

NameError: name 'true_labels' is not defined

In [ ]:
from sklearn.metrics import f1_score, recall_score, precision_score


class LogisticRegression:


# Sample true labels and predicted labels (replace with your actual data)
    #true_labels = df['price_category']
# Assuming you have a model named 'model' and you're making predictions on a dataset 'X_test'
    predicted_labels = model.predict(X_test)
    true_labels = df['price_category']


# Calculate the number of correct predictions
correct_predictions = np.sum(true_labels == predicted_labels)

# Calculate the total number of predictions
total_predictions = len(true_labels)

# Calculate accuracy
accuracy = correct_predictions / total_predictions

print("Accuracy:", accuracy)

# Function to calculate accuracy
    def accuracy(true_labels, predicted_labels):
        correct_predictions = np.sum(true_labels == predicted_labels)
        total_predictions = len(true_labels)
        return correct_predictions / total_predictions

# Function to calculate precision for a specific class
    def precision(true_labels, predicted_labels, class_label):
        true_positive = np.sum((true_labels == class_label) & (predicted_labels == class_label))
        false_positive = np.sum((true_labels != class_label) & (predicted_labels == class_label))
        return true_positive / (true_positive + false_positive)

# Function to calculate recall for a specific class
    def recall(true_labels, predicted_labels, class_label):
        true_positive = np.sum((true_labels == class_label) & (predicted_labels == class_label))
        false_negative = np.sum((true_labels == class_label) & (predicted_labels != class_label))
        return true_positive / (true_positive + false_negative)

# Function to calculate F1-score for a specific class
    def f1_score(true_labels, predicted_labels, class_label):
        prec = precision_score(true_labels, predicted_labels, class_label)
        rec = recall_score(true_labels, predicted_labels, class_label)
        return 2 * (prec * rec) / (prec + rec)

# Function to calculate macro-precision
    def macro_precision(true_labels, predicted_labels, num_classes):
        precisions = [precision(true_labels, predicted_labels, class_label) for class_label in range(num_classes)]
        return np.mean(precisions)

# Function to calculate macro-recall
    def macro_recall(true_labels, predicted_labels, num_classes):
        recalls = [recall(true_labels, predicted_labels, class_label) for class_label in range(num_classes)]
        return np.mean(recalls)

# Function to calculate macro-F1
    def macro_f1_score(true_labels, predicted_labels, num_classes):
        f1_scores = [f1_score(true_labels, predicted_labels, class_label) for class_label in range(num_classes)]
        return np.mean(f1_scores)

# Function to calculate weighted precision
    def weighted_precision(true_labels, predicted_labels, num_classes, class_weights):
        precisions = [precision(true_labels, predicted_labels, class_label) for class_label in range(num_classes)]
        weighted_precisions = [class_weights[class_label] * precisions[class_label] for class_label in range(num_classes)]
        return np.sum(weighted_precisions) / np.sum(class_weights)

# Function to calculate weighted recall
    def weighted_recall(true_labels, predicted_labels, num_classes, class_weights):
        recalls = [recall(true_labels, predicted_labels, class_label) for class_label in range(num_classes)]
        weighted_recalls = [class_weights[class_label] * recalls[class_label] for class_label in range(num_classes)]
        return np.sum(weighted_recalls) / np.sum(class_weights)

# Function to calculate weighted F1-score
    def weighted_f1_score(true_labels, predicted_labels, num_classes, class_weights):
        f1_scores = [f1_score(true_labels, predicted_labels, class_label) for class_label in range(num_classes)]
        weighted_f1_scores = [class_weights[class_label] * f1_scores[class_label] for class_label in range(num_classes)]
        return np.sum(weighted_f1_scores) / np.sum(class_weights)

# Calculate class weights (replace with your own class distribution)
class_weights = [0.2, 0.3, 0.2, 0.3]

# Calculate and print the metrics
print("Accuracy:", accuracy(true_labels, predicted_labels))
print("Macro Precision:", macro_precision(true_labels, predicted_labels, num_classes=4))
print("Macro Recall:", macro_recall(true_labels, predicted_labels, num_classes=4))
print("Macro F1 Score:", macro_f1_score(true_labels, predicted_labels, num_classes=4))
print("Weighted Precision:", weighted_precision(true_labels, predicted_labels, num_classes=4, class_weights=class_weights))
print("Weighted Recall:", weighted_recall(true_labels, predicted_labels, num_classes=4, class_weights=class_weights))
print("Weighted F1 Score:", weighted_f1_score(true_labels, predicted_labels, num_classes=4, class_weights=class_weights))

IndentationError: expected an indented block after function definition on line 11 (2055078163.py, line 12)

In [359]:
print("Length of true_labels:", len(y_test))
print("Length of predicted_labels:", len(y_pred))

Length of true_labels: 1582
Length of predicted_labels: 1582

In [ ]:
import time


class LogisticRegression:
    
    def __init__(self, k, n, method, alpha = 0.001, max_iter=5000):
        self.k = k
        self.n = n
        self.alpha = alpha
        self.max_iter = max_iter
        self.method = method
    
    def fit(self, X, Y):
        self.W = np.random.rand(self.n, self.k)
        self.losses = []
        
        if self.method == "batch":
            start_time = time.time()
            for i in range(self.max_iter):
                loss, grad =  self.gradient(X, Y)
                self.losses.append(loss)
                self.W = self.W - self.alpha * grad
                if i % 500 == 0:
                    print(f"Loss at iteration {i}", loss)
            print(f"time taken: {time.time() - start_time}")
            
        elif self.method == "minibatch":
            start_time = time.time()
            batch_size = int(0.3 * X.shape[0])
            for i in range(self.max_iter):
                ix = np.random.randint(0, X.shape[0]) #<----with replacement
                batch_X = X[ix:ix+batch_size]
                batch_Y = Y[ix:ix+batch_size]
                loss, grad = self.gradient(batch_X, batch_Y)
                self.losses.append(loss)
                self.W = self.W - self.alpha * grad
                if i % 500 == 0:
                    print(f"Loss at iteration {i}", loss)
            print(f"time taken: {time.time() - start_time}")
            
        elif self.method == "sto":
            start_time = time.time()
            list_of_used_ix = []
            for i in range(self.max_iter):
                idx = np.random.randint(X.shape[0])
                while i in list_of_used_ix:
                    idx = np.random.randint(X.shape[0])
                X_train = X[idx, :].reshape(1, -1)
                Y_train = Y[idx]
                loss, grad = self.gradient(X_train, Y_train)
                self.losses.append(loss)
                self.W = self.W - self.alpha * grad
                
                list_of_used_ix.append(i)
                if len(list_of_used_ix) == X.shape[0]:
                    list_of_used_ix = []
                if i % 500 == 0:
                    print(f"Loss at iteration {i}", loss)
            print(f"time taken: {time.time() - start_time}")
            
        else:
            raise ValueError('Method must be one of the followings: "batch", "minibatch" or "sto".')
        
        
    def gradient(self, X, Y):
        m = X.shape[0]
        h = self.h_theta(X, self.W)
        loss = - np.sum(Y*np.log(h)) / m
        error = h - Y
        grad = self.softmax_grad(X, error)
        return loss, grad

    def softmax(self, theta_t_x):
        return np.exp(theta_t_x) / np.sum(np.exp(theta_t_x), axis=1, keepdims=True)

    def softmax_grad(self, X, error):
        return  X.T @ error

    def h_theta(self, X, W):
        '''
        Input:
            X shape: (m, n)
            w shape: (n, k)
        Returns:
            yhat shape: (m, k)
        '''
        return self.softmax(X @ W)
    
    def predict(self, X_test):
        return np.argmax(self.h_theta(X_test, self.W), axis=1)
    
    def plot(self):
        plt.plot(np.arange(len(self.losses)) , self.losses, label = "Train Losses")
        plt.title("Losses")
        plt.xlabel("epoch")
        plt.ylabel("losses")
        plt.legend()

In [ ]:
from sklearn.metrics import classification_report


model = LogisticRegression(k, X_train.shape[1], "minibatch")
model.fit(X_train, Y_train_encoded)
yhat = model.predict(X_test)
model.plot()
print("=========Classification report=======")
print("Report: ", classification_report(y_test, yhat))

ValueError: the 'keepdims' parameter is not supported in the pandas implementation of sum()

In [ ]:
df

,selling_price,km_driven,engine,seats,age,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,transmission_Automatic,transmission_Manual,seller_Dealer,seller_Individual,seller_Trustmark Dealer,is_FirstHand,is_SecondHand,is_TestDrive,price_category
0,450000,145500,12,5,9,0,1,0,0,0,1,0,1,0,1,0,0,1
1,370000,120000,14,5,9,0,1,0,0,0,1,0,1,0,0,1,0,1
2,158000,140000,14,5,17,0,0,0,1,0,1,0,1,0,0,1,0,1
3,225000,127000,13,5,13,0,1,0,0,0,1,0,1,0,1,0,0,1
4,130000,120000,12,5,16,0,0,0,1,0,1,0,1,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7901,320000,110000,11,5,10,0,0,0,1,0,1,0,1,0,1,0,0,1
7902,135000,119000,14,5,16,0,1,0,0,0,1,0,1,0,0,1,0,1
7903,382000,120000,12,5,14,0,1,0,0,0,1,0,1,0,1,0,0,1
7904,290000,25000,13,5,10,0,1,0,0,0,1,0,1,0,1,0,0,1
7905,290000,25000,13,5,10,0,1,0,0,0,1,0,1,0,1,0,0,1